language: bash

services: docker

env:
  - RF_API_SPEC_DEBUG=1

script:
  - ./scripts/cibuild

before_deploy:
  - pip install --user awscli

deploy:
  - provider: script
    script: scripts/cipublish rasterfoundry-staging-docs-site-us-east-1
    skip_cleanup: true
    on:
      repo: raster-foundry/raster-foundry-api-spec
      branch: develop

  - provider: script
    script: scripts/cipublish rasterfoundry-production-docs-site-us-east-1
    skip_cleanup: true
    on:
      repo: raster-foundry/raster-foundry-api-spec
      tags: true
