language: bash
services: docker
script:
- "./scripts/cibuild"
deploy:
  provider: s3
  access_key_id: 
    secure: "YYg24HWrvzMFJRNUgL/O+Mnfym4uAJNqRiWOHHiiOs9mvTmidAeht6e5x+03MyQfCILybthqysEB1rDVAWwtJd/s5rVt/Ht+YU2rU8cPSFtpCuDQ7nR+KRNlpl9p1IvvrXbZIRBQpkZZqQI0USlkWEx1KX7Hi80/gx9xB6EzbD7upnPbGbeAET5NFMJiCSQAGk+YIAEJp2Lj60QVtPDoY4uR6uKLNpHx909n2y5VG8otO/CXwgyclheRCvd5012B5uw+qvEugZdmtaZxS4wRml4sZSO7hfVPnhwplojSiRN728vkXUHc60ryev1HS1xlYURUjAi62ziNRozDX7r/8IePF5tQsyQmUHytuhv+818gr0xeJy/Gr0VbJ9PTy/BHb25XvnSK8cdKjYeCiuaF2ToE34XTNClDOVCO5f6FBSrfw+abbgQ0XaGqJVqGH34DSMvj3d/9FOf9czQbkJapBcwe9zc1xky8LTRly7MmNzT602lv6CHUdgnk3Lpfeb7K6Jn1IaPWPtJMzfhtJOb+o2DjGZ1OgNqzzfz0Hm5p2I8NGTh59BZFVqoPYW1BF0ybAm2b0puyf8Eap2kP6AFWyZdl4UOZ+KiMzGj/75waOAPaJXKYScnAIiJUjgFCtwAquCaiaI+SZDrsAJfgQlBivCvzWX/nYx+GtZHq2UwcqeA="
  secret_access_key:
    secure: "ndQB7t8DHA7ok/9GgS1BPotgHrX2D+u31+a72ZR+9BUjly0AxG6+wCXcR9FhU8pIMLToU9BmJIHtibM44oj+zXkjdSUfIP48edXC0eRnZv+9Wnz0U5voXluigRC1i64h0JgITofr+vF58+tq80J+socfmPjRfBzoMUYMEnlH+PeMxZq6+sNOu3H8ZWGK8A8yLXYPPkn54KIc7+2sKsIjZI/GYtQEQeP0lo87ndSlUXjOQzjAYhgzTs3n86ge+zT7gT7nisO7un7PC0kiaAIzLEDYpFVLLNzxjTHebVHhSvLnTx89QigLY96bsls5OOpSKeeyuflmNtaO1tzr4DiwsYdaQ2AZizM4a2kzQ1wxiq9hwucD1FIO+d83AM1Bhxj+vgtdTPk+enKvJKWDlf284x7WzhApQizlAz9XEILVOfLuxnjjlRrSegMjIJ+SLjxxbzeAZNp2f1etSd285TvFdeZZmwfT4z4SbVMovYm7uMRiF73fxIp0zHtH9oae5kJAQx5+RULodv5LP/ABgbRdoX8nfPThf71ES7IBtdtSt3wQ2fIL623ReXg/nKS+3jdzm4S7zF/mHIVYoLh+aW/ojBFcuyFashZQRHu8m2PFwtkdWglXLL0ThK8WpshWXp2LxGpB1Y5qOj4Qd7WJQ0FJoaMRJY4cIaFhUTE0jO9qEvI="
  bucket: rasterfoundry-staging-docs-site-us-east-1
  skip_cleanup: true
  upload-dir: spec
  on:
    repo: raster-foundry/raster-foundry-api-spec
    branch: master