#!/bin/bash

set -e

if [[ -n "${RF_API_SPEC_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0")
Run linters and tests."
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        # # Execute yarn tests
        # docker-compose \
        #     run --rm app \
        #     yarn run test

        # Make sure there's no difference between the two specs
        echo 'Checking for differences between specs'
        # specDiff=$(diff spec.yml spec/spec.yml)
        # echo "${specDiff}"
        # echo 'foo'
        specDiffLines=$(diff ./spec.yml ./spec/spec.yml | wc -l)
        if (("${specDiffLines}" > 0 )); then
            echo 'Difference between spec.yml in repository root and spec/spec.yml'
            exit 1
        fi
    fi
fi
