#!/bin/bash

set -e

if [[ -n "${RF_API_SPEC_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0")
Validates specs via Docker Compose.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        # Validate Raster Foundry API spec
        docker-compose run --rm app \
            yarn run validate-api-spec

        # Validate Raster Foundry Prediction API spec
        docker-compose run --rm app \
            yarn run validate-prediction-api-spec

        # Validate Raster Foundry Tile spec
        docker-compose run --rm app \
                       yarn run validate-tile-spec
    fi
fi
