#!/bin/bash

set -e

if [[ -n "${RF_API_SPEC_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n \
         "Usage: $(basename "$0")
Run linters and tests."
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        # Execute yarn tests
        docker-compose \
            run --rm app \
            yarn run test
    fi
fi