#!/bin/bash

set -e

if [[ -n "${RF_API_SPEC_DEBUG}" ]]; then
    set -x
fi

function usage() {
    echo -n "Usage: $(basename "$0")
Builds and pulls container images using docker-compose.
"
}

if [ "${BASH_SOURCE[0]}" = "${0}" ]
then
    if [ "${1:-}" = "--help" ]
    then
        usage
    else
        # Install NPM modules
        docker-compose \
            run --rm app \
            yarn --frozen-lockfile
    fi
fi